import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding 35 diverse non-real-estate advertisement banners...");

  // Clear existing ads
  await prisma.advertisement.deleteMany({});

  const sampleAds = [
    // ── 1. HIGHER EDUCATION & STUDY ABROAD ──
    {
      name: "Harvard Executive Leadership Certification 2026",
      imageUrl: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://online.harvard.edu",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: true,
      isActive: true,
      displayOrder: 1,
      clickCount: 342,
    },
    {
      name: "Study in UK - Free University Admissions & Visa Support",
      imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.studyuk.britishcouncil.org",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 2,
      clickCount: 189,
    },
    {
      name: "MIT Artificial Intelligence & Data Science Bootcamp",
      imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://executive.mit.edu",
      placement: "PROPERTIES_ONLY" as const,
      format: "QUAD_GRID" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 3,
      clickCount: 275,
    },

    // ── 2. EDTECH & CODING ──
    {
      name: "Coursera Plus - Unlimited Access to 7,000+ Verified Courses",
      imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.coursera.org",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 4,
      clickCount: 412,
    },
    {
      name: "LeetCode Premium - Master Algorithmic Tech Interviews",
      imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://leetcode.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 5,
      clickCount: 310,
    },
    {
      name: "Full Stack Web Development - 100% Career Placement Support",
      imageUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.scaler.com",
      placement: "HOME_ONLY" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 6,
      clickCount: 228,
    },

    // ── 3. FINTECH & INVESTMENTS ──
    {
      name: "Zerodha Kite - Zero Brokerage Stock & Equity Investing",
      imageUrl: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://zerodha.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 7,
      clickCount: 520,
    },
    {
      name: "Groww Mutual Funds - Start Daily SIP From Just ₹100",
      imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://groww.in",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 8,
      clickCount: 195,
    },
    {
      name: "Binance Global Digital Asset & Crypto Exchange",
      imageUrl: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.binance.com",
      placement: "PROPERTIES_ONLY" as const,
      format: "QUAD_GRID" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 9,
      clickCount: 164,
    },

    // ── 4. AUTOMOTIVE & EV ──
    {
      name: "Tesla Model Y 2026 - Experience Pure Electric Power",
      imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.tesla.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 10,
      clickCount: 480,
    },
    {
      name: "BMW i7 Luxury Electric Sedan - Test Drive Today",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.bmw.in",
      placement: "HOME_ONLY" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 11,
      clickCount: 312,
    },
    {
      name: "Royal Enfield Hunter 350 - Book Online & Get Accessories",
      imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.royalenfield.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 12,
      clickCount: 270,
    },

    // ── 5. ELECTRONICS & SMARTPHONES ──
    {
      name: "Apple iPhone 17 Pro Max - Pre-Order Titan Series",
      imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.apple.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 13,
      clickCount: 610,
    },
    {
      name: "Sony PlayStation 5 Pro - Next-Gen Gaming Bundle Deal",
      imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.playstation.com",
      placement: "PROPERTIES_ONLY" as const,
      format: "QUAD_GRID" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 14,
      clickCount: 489,
    },
    {
      name: "Samsung Galaxy Z Fold 7 Ultra Experience",
      imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.samsung.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 15,
      clickCount: 350,
    },

    // ── 6. TRAVEL, AIRLINES & HOTELS ──
    {
      name: "Emirates First Class - Book Fly Better Global Destinations",
      imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.emirates.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 16,
      clickCount: 390,
    },
    {
      name: "MakeMyTrip Holidays - Up to 40% Off International Flights",
      imageUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.makemytrip.com",
      placement: "HOME_ONLY" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 17,
      clickCount: 512,
    },
    {
      name: "Taj Hotels & Palaces - Luxury Heritage Getaways",
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.tajhotels.com",
      placement: "PROPERTY_DETAIL_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 18,
      clickCount: 220,
    },

    // ── 7. E-COMMERCE & FASHION ──
    {
      name: "Nike Air Max 2026 Collection - Shop Premium Sneakers",
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.nike.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 19,
      clickCount: 430,
    },
    {
      name: "Sephora Beauty Fest - 30% Off Premium Skincare & Cosmetics",
      imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.sephora.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 20,
      clickCount: 295,
    },
    {
      name: "Zara Autumn/Winter Designer Fashion Launch",
      imageUrl: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.zara.com",
      placement: "PROPERTIES_ONLY" as const,
      format: "QUAD_GRID" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 21,
      clickCount: 180,
    },

    // ── 8. HEALTH & FITNESS ──
    {
      name: "Cult.fit Pass Elite - Unlimited Gyms & Fitness Centers",
      imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.cult.fit",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 22,
      clickCount: 388,
    },
    {
      name: "Myprotein Whey Isolate - Extra 25% Off Code FIT2026",
      imageUrl: "https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.myprotein.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 23,
      clickCount: 210,
    },
    {
      name: "Apple Watch Ultra 3 - Fitness & Altitude Summit Tracker",
      imageUrl: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.apple.com/watch",
      placement: "HOME_ONLY" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 24,
      clickCount: 345,
    },

    // ── 9. SAAS & CLOUD SERVICES ──
    {
      name: "Vercel Enterprise Cloud Hosting & Global Edge Infra",
      imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://vercel.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 25,
      clickCount: 460,
    },
    {
      name: "Figma Professional - Collaborate & Design Interfaces Faster",
      imageUrl: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.figma.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 26,
      clickCount: 378,
    },
    {
      name: "ChatGPT Plus & Team Intelligence Workspace Subscription",
      imageUrl: "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://chatgpt.com",
      placement: "PROPERTIES_ONLY" as const,
      format: "QUAD_GRID" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 27,
      clickCount: 720,
    },

    // ── 10. ENTERTAINMENT & GAMING ──
    {
      name: "Netflix Premium 4K HDR - Unlimited Movies & TV Shows",
      imageUrl: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.netflix.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 28,
      clickCount: 680,
    },
    {
      name: "Spotify Family Premium - 3 Months Free Music Trial",
      imageUrl: "https://images.unsplash.com/photo-1614680376593-902f749f7b64?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.spotify.com",
      placement: "HOME_ONLY" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 29,
      clickCount: 490,
    },
    {
      name: "Steam Summer Gaming Festival - Up to 85% Off AAA Titles",
      imageUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://store.steampowered.com",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 30,
      clickCount: 540,
    },

    // ── 11. FOOD & GOURMET ──
    {
      name: "Starbucks Coffee Rewards - Get Free Handcrafted Drinks",
      imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.starbucks.in",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 31,
      clickCount: 410,
    },
    {
      name: "Zomato Gold - Unlimited Free Restaurant Deliveries",
      imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.zomato.com",
      placement: "PROPERTY_DETAIL_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 32,
      clickCount: 380,
    },
    {
      name: "Nespresso Vertuo Espresso Pod Coffee Maker",
      imageUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.nespresso.com",
      placement: "PROPERTIES_ONLY" as const,
      format: "QUAD_GRID" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 33,
      clickCount: 260,
    },
    {
      name: "Uber Premier Intercity Ride Booking Special",
      imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.uber.com",
      placement: "BOTH" as const,
      format: "FULL_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 34,
      clickCount: 325,
    },
    {
      name: "Audible Premium Plus - 2 Free Audiobooks On Sign Up",
      imageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80",
      targetUrl: "https://www.audible.in",
      placement: "INNER_ONLY" as const,
      format: "HALF_WIDTH" as const,
      isExclusive: false,
      isActive: true,
      displayOrder: 35,
      clickCount: 290,
    },
  ];

  for (const ad of sampleAds) {
    await prisma.advertisement.create({ data: ad });
  }

  console.log(`Successfully seeded ${sampleAds.length} diverse non-real-estate advertisement banners!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
